### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [dsudbury/prj-rev-bwfs-dasmoto#6]
**GRADE**: Meets Expectations

**SUMMARY**: Great start on this project. The site looks great and you did an excellent job keeping your styling clean and concise throughout. Nice use of relative file paths to link to your local images throughout the html as well!

Behind the scenes, make sure to include the alt attribute on your img elements to ensure that a wider variety of users have access to that information. Also, try to keep your indentation as consistent as possible. Everything nested to the same level should be indented the same amount. Clean, concise code is crucial and only becomes more so as your projects grow in size and complexity.

As a next step, try using a relative file path to link to the background image from your css. More info about relative file paths can be found [here](http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/).

Have fun and keep up the good work!

**Comment by dsudbury** [comment]
Thanks!
